import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, basename } from 'path';
import { paths } from './config.js';
import { logger } from './logger.js';

const ASSETS_DIR = paths.assets;
const SCRIPTS_DIR = join(paths.wiki, '..', 'scripts', 'outputs');

mkdirSync(ASSETS_DIR, { recursive: true });
mkdirSync(SCRIPTS_DIR, { recursive: true });

export function generateMarpSlide(title, content, options = {}) {
  const { theme = 'default' } = options;
  
  const slide = `---
marp: true
theme: ${theme}
paginate: true
---

# ${title}

${content}

---

> Generated by 记不下
`;
  
  return slide;
}

export function generateMarpDeck(title, slides) {
  let deck = `---
marp: true
title: ${title}
theme: default
paginate: true
---

# ${title}

${slides[0]?.content || ''}

`;

  for (let i = 1; i < slides.length; i++) {
    const slide = slides[i];
    deck += `---\n\n# ${slide.title}\n\n${slide.content}\n\n`;
  }
  
  deck += `---\n\n# Summary\n\n`;
  deck += `Generated on ${new Date().toISOString()}\n`;
  
  return deck;
}

export function generateMarkdownDiagram(text, type = 'mermaid') {
  if (type === 'mermaid') {
    return `\`\`\`mermaid\n${text}\n\`\`\``;
  }
  
  if (type === 'plantuml') {
    return `\`\`\`plantuml\n${text}\n\`\`\``;
  }
  
  return text;
}

export function generateTimeline(events, options = {}) {
  const { title = 'Timeline' } = options;
  
  let md = `# ${title}\n\n`;
  md += `## Timeline\n\n`;
  
  for (const event of events) {
    const date = event.date || 'Unknown';
    const desc = event.description || event.text || '';
    md += `- **${date}**: ${desc}\n`;
  }
  
  md += `\n---\n`;
  md += `_Generated: ${new Date().toISOString()}_\n`;
  
  return md;
}

export function generateComparisonTable(items, criteria, options = {}) {
  const { title = 'Comparison' } = options;
  
  let md = `# ${title}\n\n`;
  md += `| ${criteria.join(' | ')} |\n`;
  md += `| ${criteria.map(() => '---').join(' | ')} |\n`;
  
  for (const item of items) {
    md += `| ${criteria.map(c => item[c] || '-').join(' | ')} |\n`;
  }
  
  md += `\n---\n`;
  md += `_Generated: ${new Date().toISOString()}_\n`;
  
  return md;
}

export function saveOutput(content, filename, type = 'md') {
  const ext = type === 'md' ? '.md' : type === 'html' ? '.html' : type === 'py' ? '.py' : '.txt';
  const filepath = join(type === 'py' ? SCRIPTS_DIR : ASSETS_DIR, `${filename}${ext}`);
  writeFileSync(filepath, content);
  logger.info(`[output] Saved: ${filepath}`);
  return filepath;
}

export function saveToWiki(content, filename) {
  const filepath = join(paths.articles, filename);
  writeFileSync(filepath, content);
  logger.info(`[output] Saved to wiki: ${filepath}`);
  return filepath;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const cmd = process.argv[2];
  
  if (cmd === 'slide') {
    const title = process.argv[3] || 'Slide';
    const content = process.argv[4] || 'Content here';
    const slide = generateMarpSlide(title, content);
    console.log(slide);
  }
  
  if (cmd === 'timeline') {
    const events = [
      { date: '2024-01', description: 'Event 1' },
      { date: '2024-02', description: 'Event 2' }
    ];
    console.log(generateTimeline(events));
  }
}