import { readFileSync, writeFileSync, mkdirSync, execSync } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIG = JSON.parse(readFileSync(join(__dirname, '..', 'config.json'), 'utf-8'));

const ASSETS_DIR = join(__dirname, '..', CONFIG.paths.assets);
const SCRIPTS_DIR = join(__dirname, '..', 'scripts', 'outputs');

mkdirSync(ASSETS_DIR, { recursive: true });
mkdirSync(SCRIPTS_DIR, { recursive: true });

export function generateMarpSlide(title, content, options = {}) {
  const { theme = 'default' } = options;
  
  const slide = `---
marp: true
theme: ${theme}
paginate: true
---

# ${title}

${content}

---

> Generated by 记不下
`;
  
  return slide;
}

export function generateMarpDeck(title, slides) {
  let deck = `---
marp: true
title: ${title}
theme: default
paginate: true
---

# ${title}

${slides[0]?.content || ''}

`;

  for (let i = 1; i < slides.length; i++) {
    const slide = slides[i];
    deck += `---\n\n# ${slide.title}\n\n${slide.content}\n\n`;
  }
  
  deck += `---\n\n# Summary\n\n`;
  deck += `Generated on ${new Date().toISOString()}\n`;
  
  return deck;
}

export function generateChart(data, type = 'bar', options = {}) {
  const { title = 'Chart', xLabel = '', yLabel = '' } = options;
  
  const chartJs = `<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body { margin: 0; padding: 20px; }
    canvas { max-width: 800px; margin: 0 auto; }
  </style>
</head>
<body>
  <canvas id="chart"></canvas>
  <script>
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {
      type: '${type}',
      data: ${JSON.stringify(data)},
      options: {
        responsive: true,
        maintainAspectRatio: true,
        plugins: {
          title: {
            display: true,
            text: '${title}'
          },
          legend: {
            display: ${data.datasets?.length > 1 ? 'true' : 'false'}
          }
        },
        scales: {
          x: {
            display: true,
            title: { display: true, text: '${xLabel}' }
          },
          y: {
            display: true,
            title: { display: true, text: '${yLabel}' }
          }
        }
      }
    });
  </script>
</body>
</html>`;
  
  return chartJs;
}

export function generateMatplotlibScript(data, type = 'bar', options = {}) {
  const { title = 'Chart', xLabel = '', yLabel = '', filename = 'chart.png', showValues = false } = options;
  
  const labels = JSON.stringify(data.labels || []);
  const datasets = data.datasets || [{ data: data.data || [] }];
  
  let pythonCode = `#!/usr/bin/env python3
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

labels = ${labels}
`;

  for (let i = 0; i < datasets.length; i++) {
    const ds = datasets[i];
    const dataArray = JSON.stringify(ds.data || []);
    const label = ds.label || `Dataset ${i + 1}`;
    const color = ds.color || null;
    pythonCode += `\ndata_${i} = ${dataArray}\n`;
    if (color) {
      pythonCode += `color_${i} = '${color}'\n`;
    }
  }

  pythonCode += `
fig, ax = plt.subplots(figsize=(10, 6))
`;

  if (type === 'bar') {
    pythonCode += `
x = np.arange(len(labels))
width = 0.35
`;
    for (let i = 0; i < datasets.length; i++) {
      if (datasets[i].color) {
        pythonCode += `ax.bar(x - width/2 + ${i}*width, data_${i}, width, label='${datasets[i].label}', color=color_${i})\n`;
      } else {
        pythonCode += `ax.bar(x - width/2 + ${i}*width, data_${i}, width, label='${datasets[i].label}')\n`;
      }
    }
    pythonCode += `ax.set_xticks(x)\nax.set_xticklabels(labels)\n`;
  } else if (type === 'line') {
    for (let i = 0; i < datasets.length; i++) {
      if (datasets[i].color) {
        pythonCode += `ax.plot(labels, data_${i}, marker='o', label='${datasets[i].label}', color=color_${i})\n`;
      } else {
        pythonCode += `ax.plot(labels, data_${i}, marker='o', label='${datasets[i].label}')\n`;
      }
    }
  } else if (type === 'pie') {
    pythonCode += `ax.pie(data_0, labels=labels, autopct='%1.1f%%', startangle=90)\n`;
  } else if (type === 'scatter') {
    for (let i = 0; i < datasets.length; i++) {
      if (datasets[i].color) {
        pythonCode += `ax.scatter(range(len(data_${i})), data_${i}, label='${datasets[i].label}', color=color_${i})\n`;
      } else {
        pythonCode += `ax.scatter(range(len(data_${i})), data_${i}, label='${datasets[i].label}')\n`;
      }
    }
  }

  pythonCode += `
ax.set_xlabel('${xLabel}')
ax.set_ylabel('${yLabel}')
ax.set_title('${title}')
`;

  if (datasets.length > 1) {
    pythonCode += `ax.legend()\n`;
  }

  if (showValues && type === 'bar') {
    pythonCode += `
for i, (container, d) in enumerate(zip(ax.containers, [${datasets.map((_, i) => `data_${i}`).join(', ')}])):
    ax.bar_label(container, labels=[f'{v:.0f}' for v in d], label_type='edge')
`;
  }

  pythonCode += `
plt.tight_layout()
plt.savefig('${filename}', dpi=150)
print(f'Saved: ${filename}')
`;
  
  return pythonCode;
}

export async function generateMatplotlib(data, type = 'bar', options = {}) {
  const { title = 'Chart', xLabel = '', yLabel = '', savePng = true } = options;
  
  const timestamp = Date.now();
  const scriptName = `chart_${timestamp}.py`;
  const imageName = `chart_${timestamp}.png`;
  
  const scriptPath = join(SCRIPTS_DIR, scriptName);
  const imagePath = join(ASSETS_DIR, imageName);
  
  const script = generateMatplotlibScript(data, type, {
    ...options,
    title,
    xLabel,
    yLabel,
    filename: imagePath
  });
  
  writeFileSync(scriptPath, script);
  console.log(`[output] Generated matplotlib script: ${scriptPath}`);
  
  if (savePng) {
    try {
      execSync(`python3 "${scriptPath}"`, { stdio: 'inherit' });
      console.log(`[output] Generated image: ${imagePath}`);
      return { script: scriptPath, image: imagePath };
    } catch (e) {
      console.error('[output] Matplotlib generation failed:', e.message);
      return { script: scriptPath, image: null, error: e.message };
    }
  }
  
  return { script: scriptPath, image: null };
}

export function generateMarkdownDiagram(text, type = 'mermaid') {
  if (type === 'mermaid') {
    return `\`\`\`mermaid\n${text}\n\`\`\``;
  }
  
  if (type === 'plantuml') {
    return `\`\`\`plantuml\n${text}\n\`\`\``;
  }
  
  return text;
}

export function generateTimeline(events, options = {}) {
  const { title = 'Timeline' } = options;
  
  let md = `# ${title}\n\n`;
  md += `## Timeline\n\n`;
  
  for (const event of events) {
    const date = event.date || 'Unknown';
    const desc = event.description || event.text || '';
    md += `- **${date}**: ${desc}\n`;
  }
  
  md += `\n---\n`;
  md += `_Generated: ${new Date().toISOString()}_\n`;
  
  return md;
}

export function generateComparisonTable(items, criteria, options = {}) {
  const { title = 'Comparison' } = options;
  
  let md = `# ${title}\n\n`;
  md += `| ${criteria.join(' | ')} |\n`;
  md += `| ${criteria.map(() => '---').join(' | ')} |\n`;
  
  for (const item of items) {
    md += `| ${criteria.map(c => item[c] || '-').join(' | ')} |\n`;
  }
  
  md += `\n---\n`;
  md += `_Generated: ${new Date().toISOString()}_\n`;
  
  return md;
}

export function saveOutput(content, filename, type = 'md') {
  const ext = type === 'md' ? '.md' : type === 'html' ? '.html' : type === 'py' ? '.py' : '.txt';
  const filepath = join(type === 'py' ? SCRIPTS_DIR : ASSETS_DIR, `${filename}${ext}`);
  writeFileSync(filepath, content);
  console.log(`[output] Saved: ${filepath}`);
  return filepath;
}

export function saveToWiki(content, filename) {
  const WIKI_DIR = join(__dirname, '..', CONFIG.paths.wiki);
  const ARTICLES_DIR = join(__dirname, '..', CONFIG.paths.articles);
  const filepath = join(ARTICLES_DIR, filename);
  writeFileSync(filepath, content);
  console.log(`[output] Saved to wiki: ${filepath}`);
  return filepath;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const cmd = process.argv[2];
  
  if (cmd === 'slide') {
    const title = process.argv[3] || 'Slide';
    const content = process.argv[4] || 'Content here';
    const slide = generateMarpSlide(title, content);
    console.log(slide);
  }
  
  if (cmd === 'chart') {
    const data = {
      labels: ['A', 'B', 'C', 'D'],
      datasets: [{ data: [10, 20, 15, 25], label: 'Values' }]
    };
    const html = generateChart(data, 'bar', { title: 'Sample Chart' });
    saveOutput(html, 'chart_sample', 'html');
  }
  
  if (cmd === 'matplotlib') {
    const data = {
      labels: ['A', 'B', 'C', 'D'],
      datasets: [{ data: [10, 20, 15, 25], label: 'Values' }]
    };
    generateMatplotlib(data, 'bar', { title: 'Sample Chart', xLabel: 'Category', yLabel: 'Value' });
  }
  
  if (cmd === 'timeline') {
    const events = [
      { date: '2024-01', description: 'Event 1' },
      { date: '2024-02', description: 'Event 2' }
    ];
    console.log(generateTimeline(events));
  }
}